name: Sync to AWS

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      repository_name:
        description: "The name of the GitHub repository to sync to AWS CodeCommit"
        required: true
        # options:
        #   - ""
      aws_region:
        description: "The AWS CodeCommit region"
        required: true
        default: us-east-1

concurrency:
  group: sync-to-aws

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.0.3
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region:

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: ${{ inputs.repository_name }}
          aws_region: ${{ inputs.aws_region }}
