# This workflow will sync a repository from AWS CodeCommit to GitHub
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Sync from AWS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: sync

jobs:
  sync-from-aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
