name: Sync to AWS

on:
  # push:
  #   branches:
  #     - "main"
  workflow_dispatch:
    inputs:
      aws_repository_name:
        description: "The name of the GitHub repository to sync to AWS CodeCommit"
        required: true
        # options:
        #   - ""
      gh_repository_name:
        description: "The name of the GitHub repository to sync to AWS CodeCommit"
        required: true
        # options:
        #   - ""
      aws_region:
        description: "The AWS CodeCommit region"
        required: true
        default: us-east-1

concurrency:
  group: sync-to-aws

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: ${{ inputs.aws_repository_name }}
          aws_region: ${{ inputs.aws_region }}
